import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";
import style from "./page.module.css";
import { BsCart3 } from "react-icons/bs";
import { IoIosMoon } from "react-icons/io";
const inter = Inter({ subsets: ["latin"] });
const isActive=true;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className={style["header-top"]}>
            <div className={style.container}>
            <nav className={style.auth}>
              <Link href="#">sign up</Link>
              <Link href="#">Create account</Link>
            </nav>
            </div>
          </div>
          <div className={style["header-bottom"]}>
         <div  className={style.container}>
       <div className={style['header-item']}>
     <Link href="/" className={style["header-logo"]}>
              <h1>C</h1>
            </Link>
            <nav className={style["header-link"]}>
          <Link href="/" >Home</Link>
          <Link href="/about" >About Us</Link>
          <Link href="/products" >Products</Link>
          <Link href="/contact" >Contact</Link>
          </nav>
          <div className={style.cart}>
          <IoIosMoon />
          <BsCart3 />
          </div>
     </div>
         </div>
          </div>
          
        </header>
        {children}
      </body>
    </html>
  );
}
